[[pages]]
path = "pages/actas.py"
hidden = true

[[pages]]
path = "pages/boletin.py"
hidden = true

[[pages]]
path = "pages/editor_zonas.py"
hidden = true

[[pages]]
path = "pages/generar_informe.py"
hidden = true

[[pages]]
path = "pages/hacerlapc.py"
hidden = true

[[pages]]
path = "pages/informe_utiles.py"
hidden = true

[[pages]]
path = "pages/mapazona.py"
hidden = true

[[pages]]
path = "pages/medicamentosonco.py"
hidden = true

[[pages]]
path = "pages/pagactasinspectores.py"
hidden = true

[[pages]]
path = "pages/reclamos.py"
hidden = true

[[pages]]
path = "pages/zonas.py"
hidden = true
